version: '3.8'

services:
  img2svg:
    image: ghcr.io/depoll/img-to-printable-svg:latest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      # Mount input and output directories
      - ./input:/app/input:ro
      - ./output:/app/output
    environment:
      - PYTHONUNBUFFERED=1
    # Override the default command to process a specific file
    # Uncomment and modify the command below to process files
    # command: ["/app/input/example.jpg", "/app/output/example.svg", "-c", "8"]
    
  # Web service for interactive use (optional)
  img2svg-web:
    image: ghcr.io/depoll/img-to-printable-svg:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./input:/app/input:ro
      - ./output:/app/output
    environment:
      - PYTHONUNBUFFERED=1
    # Run a simple web server (would need additional web interface implementation)
    command: ["python", "-m", "http.server", "8080"]
    profiles:
      - web