version: '3.8'

services:
  # Web service - runs by default
  web:
    image: ghcr.io/depoll/img-to-printable-svg:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./input:/app/input:ro
      - ./output:/app/output
      - ./temp:/app/temp
    environment:
      - PYTHONUNBUFFERED=1
      - PORT=5000
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
  # CLI service - for command-line processing
  cli:
    image: ghcr.io/depoll/img-to-printable-svg:latest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./input:/app/input:ro
      - ./output:/app/output
    environment:
      - PYTHONUNBUFFERED=1
    # Override with your own command
    entrypoint: ["python", "img2svg.py"]
    command: ["--help"]
    profiles:
      - cli